server:
  port: 8080
spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源，主要处理增删改的请求
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://8.130.138.62:3306/reggie
        username: root
        password: 123456
      # 从数据源，主要处理查询的请求
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://8.130.121.205/reggie
        username: root
        password: 123456
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
    # 允许bean定义覆盖
    main:
      allow-bean-definition-overriding: true
  application:
    name: reggie_take_out
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    # 在这里更改数据源，使用阿里的数据源
#    type: com.alibaba.druid.pool.DruidDataSource
  # redis的相关配置
  redis:
    host: localhost
    port: 6379
    database: 0
#    password:
#  配置缓存的存活时间
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#      配置逻辑删除的功能
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    # 开启控制台的banner
    banner: true

reggie:
  path: E:/img/
